/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MovementCreate$Params {
      body?: {
'details'?: Array<{
'expirationDate'?: string;
'idLot'?: string | null;
'idProduct'?: string;
'idSupplier'?: string;
'quantity'?: number;
'unitCost'?: number;
}>;
'idUser'?: string;
'observation'?: string;
'type'?: string;
}
}

export function movementCreate(http: HttpClient, rootUrl: string, params?: MovementCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, movementCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

movementCreate.PATH = '/movement/create';
