/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface ReniecConsultarDni$Params {
    numero: string;
}

export interface ReniecDniResponse {
    first_name: string;
    first_last_name: string;
    second_last_name: string;
    full_name: string;
    document_number: string;
}

export function reniecConsultarDni(http: HttpClient, rootUrl: string, params: ReniecConsultarDni$Params, context?: HttpContext): Observable<StrictHttpResponse<ReniecDniResponse>> {
    const rb = new RequestBuilder(rootUrl, reniecConsultarDni.PATH, 'get');
    if (params) {
        rb.query('numero', params.numero, {});
    }

    return http.request(
        rb.build({ responseType: 'json', accept: 'application/json', context })
    ).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return r as StrictHttpResponse<ReniecDniResponse>;
        })
    );
}

reniecConsultarDni.PATH = '/v1/reniec/dni';